/// Generated by AssetsRefGenerator on 2021/11/07
class Res {
  static const String bxs_map_pin = "assets/images/bxs_map_pin.png";
  static const String delivery_man_1 = "assets/images/delivery_man_1.png";
  static const String delivery_man_2 = "assets/images/delivery_man_2.png";
  static const String ellipse_two = "assets/images/ellipse_two.png";
  static const String friends_app_one = "assets/images/friends_app_one.png";
  static const String friends_app_two = "assets/images/friends_app_two.png";
  static const String img_appel = "assets/images/img_appel.png";
  static const String img_menu = "assets/images/img_menu.png";
  static const String img_telegram = "assets/images/img_telegram.png";
  static const String logo = "assets/icons/logo.png";
  static const String logo_app = "assets/images/logo_app.png";
  static const String person_img_profil = "assets/images/person_img_profil.png";
  static const String profil_img = "assets/images/profil_img.png";
  static const String simple_logo = "assets/images/simple_logo.png";
}
